apps/account/urls.py
from rest_framework_nested import routers
from django.conf.urls import patterns, url, include
from . import views

router = routers.SimpleRouter()
router.register('users', views.UserViewSet, base_name='users')
router.register('user-technologies', views.UserTechnologyViewSet, base_name='user-technologies')

urlpatterns = patterns(
    '',
    url(r'^api/', include(router.urls)),
    url(r'^api-auth-token/$', views.ObtainAuthToken.as_view()),
    url(r'^profile/register/$', views.RegisterView.as_view(), name='register'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^password/reset/(?P<id>[0-9]*)/(?P<key>[-\w\d]+)$', views.PasswordResetView.as_view(),
        name='password_reset'),
    url(r'^password/send-reset/$', views.SendPasswordResetMailView.as_view(), name='send_password_reset'),
    url(r'^email/send-verify/$', views.SendConfirmEmailView.as_view(), name='resend_email_confirm'),
    url(r'^email/confirm/(?P<id>[0-9]*)/(?P<key>[-\w\d]+)$', views.email_confirm_view, name='email_confirm'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib import admin

from apps.core.views import home_view


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.account.urls', namespace="account")),
    url(r'^', include('apps.projects.urls', namespace="projects")),
    url(r'^', include('apps.tasks.urls', namespace="tasks")),
    url(r'^', include('apps.core.urls', namespace="core")),
    url(r'^', include('apps.knowledge.urls', namespace="knowledge")),
    url(r'^google', include('apps.google.urls')),
    url(r'^thank-you/$', TemplateView.as_view(template_name="thankyou.html"), name="thankyou"),
    url(r'^/error/$', TemplateView.as_view(template_name="error.html"), name="error"),
    url(r'^$', home_view, name="home"),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns(
    '',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}))

templates/navs/admin.html
<li><a href="#"><i class="fa fa-fw fa-user"></i> {{user.name}}</a></li>
<li><a href="{% url 'logout' %}"><i class="fa fa-fw fa-sign-out"></i> Logout</a></li>

templates/navs/base.html
<nav class="navbar navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">App_Name</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        {% include request.nav %}
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

templates/navs/guest.html
<li><a href="{% url 'account:login' %}"><i class="fa fa-fw fa-sign-in"></i> Login</a></li>
<li><a href="{% url 'account:register' %}" title="Register"><i class="fa fa-fw fa-user"></i> Register</a></li>